server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # config.js não pode ser cacheado (é gerado por env no start do container)
  location = /config.js {
    add_header Cache-Control "no-store";
  }

  # SPA: qualquer rota cai no index.html
  location / {
    try_files $uri $uri/ /index.html;
  }
}
